#NAME: ,Kana Yabuno
#EMAIL: ,kana0111@g.ucla.edu
#ID: ,404849285

default:
	cp lab3b.py lab3b
	chmod +x lab3b

dist:
	tar -cvzf lab3b-404849285.tar.gz lab3b.py Makefile README
clean:
	rm -f lab3b-404849285.tar.gz lab3b