#NAME:Feilan Wang,Kana Yabuno
#EMAIL:wangfeilan@hotmail.com,kana0111@g.ucla.edu
#ID:104796844,404849285

default:
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py

dist:
	tar -cvzf lab3b-104796844.tar.gz lab3b.py Makefile README
clean:
	rm -f lab3b-104796844.tar.gz lab3b
