#NAME: Feilan Wang
#EMAIL: wangfeilan@hotmail.com
#ID: 104796844

CC= gcc
CFLAGS = -Wall -Wextra -g

default: 
	${CC} ${CFLAGS} -o lab3a lab3a.c

dist:
	tar -czvf lab3a-104796844.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	-rm -f lab3a-104796844.tar.gz lab3a
